---
title: "Brainvr.R showcase of loading and preprocessing"
author: "Lukáš hejtmy Hejtmánek"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Loading single experiemnt
Loading single experimet the first time

```{r}
library(brainvr.R)
dir_path <- system.file("extdata", package = "brainvr.R")
obj <- load_experiment(dir_path)
```
#Preprocessing and saving dta
```{r}
if(!is_player_preprocessed(obj$data$player_log)){
  obj$data$player_log <- preprocess_player_log(obj$data$player_log)
  save_preprocessed_player(dir_path, obj$data$player_log, obj$timestamp)
}
```

The next time you are loading the log, you will load the processed automatically

Loading processed player log
```{r}
obj <- load_experiment(dir_path)
```

# Recentering map
IN case we need a new offset, we can do that as well
```{r}
obj <- translate_positions(obj, c(33.5, 0, 47.75))
obj <- mirror_axes(obj)
```


# Visualising
Plotting player path
```{r}
#set constraints
obj$map_limits <- list(x = c(-5, 105), y = c(-5, 105))
plot_trial_path(obj, 1)
```